version: '3.9'

services:
  ccbe:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=.docker-cache
      cache_to:
        - type=local,dest=.docker-cache,mode=max
    env_file: .env
    ports:
      - "10034:10034"
    volumes:
      - ./persistent_storage:/app/persistent_storage
    restart: unless-stopped
